version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-calculator
    container_name: laravel-calculator-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: laravel-calculator-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
